version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: cargo
    directory: '/build'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: '/napi-derive'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: '/napi'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: '/sys'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
