version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
