[package]
name = "napi-rs"
version = "0.1.0"
authors = ["Nathan Sobo <nathan@github.com>", "Yinan Long <lynweklm@gmail.com>"]
license = "MIT"

[dependencies]
futures = "0.3.1"

[build-dependencies]
bindgen = "0.52"
cc = "1.0"
glob = "0.3"
semver = "0.9"
