[package]
name = "napi"
version = "0.4.13"
authors = ["Nathan Sobo <nathan@github.com>", "Yinan Long <lynweklm@gmail.com>"]
license = "MIT"
description = "N-API bindings"
readme = "README.md"
repository = "https://github.com/napi-rs/napi-rs"
keywords = ["NodeJS", "FFI", "NAPI", "n-api"]
edition = "2018"

[features]
libuv = ["futures"]
tokio_rt = ["futures", "tokio", "once_cell"]
serde-json = ["serde", "serde_json"]
latin1 = ["encoding_rs"]

[dependencies]
napi-sys = { version = "0.4", path = "../sys" }

[dependencies.encoding_rs]
version = "0.8"
optional = true

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.tokio]
version = "0.2"
features = ["rt-core", "rt-threaded", "sync"]
optional = true

[dependencies.once_cell]
version = "1.4"
optional = true

[dependencies.serde]
version = "1"
optional = true

[dependencies.serde_json]
version = "1"
optional = true

[build-dependencies]
napi-build = { version = "0.2", path = "../build" }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "napidocsrs"]
