[package]
name = "napi-rs"
version = "0.1.0"
authors = ["Nathan Sobo <nathan@github.com>", "Yinan Long <lynweklm@gmail.com>"]
license = "MIT"

[dependencies]
futures = { version = "0.3", features = ["default", "thread-pool"] }

[target.'cfg(windows)'.build-dependencies]
flate2 = "1.0"
reqwest = { version = "0.10", features = ["native-tls", "blocking"] }
tar = "0.4"

[build-dependencies]
bindgen = "0.53.1"
cc = "1.0"
glob = "0.3"
napi-build = { path = "../build" }
regex = "1.3"
semver = "0.9"