[package]
name = "napi-rs"
version = "0.3.1"
authors = ["Nathan Sobo <nathan@github.com>", "Yinan Long <lynweklm@gmail.com>"]
license = "MIT"
description = "N-API bindings"
readme = "README.md"
repository = "https://github.com/Brooooooklyn/napi-rs"
keywords = ["NodeJS", "FFI", "NAPI", "n-api"]
edition = "2018"

[features]
libuv = ["futures"]
tokio_rt = ["futures", "tokio", "once_cell"]

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.tokio]
version = "0.2"
features = ["rt-core", "rt-threaded", "sync"]
optional = true

[dependencies.once_cell]
version = "1.4"
optional = true


[target.'cfg(windows)'.build-dependencies]
flate2 = "1.0"
reqwest = { version = "0.10", features = ["native-tls", "blocking"] }
tar = "0.4"

[build-dependencies]
bindgen = "0.54"
glob = "0.3"
napi-build = { version = "0.1", path = "../build" }
regex = "1.3"
semver = "0.10"
