[package]
name = "napi-rs"
version = "0.3.1"
authors = ["Nathan Sobo <nathan@github.com>", "Yinan Long <lynweklm@gmail.com>"]
license = "MIT"
description = "N-API bindings"
readme = "README.md"
repository = "https://github.com/Brooooooklyn/napi-rs"
keywords = ["NodeJS", "FFI", "NAPI", "n-api"]
edition = "2018"

[target.'cfg(windows)'.build-dependencies]
flate2 = "1.0"
reqwest = { version = "0.10", features = ["native-tls", "blocking"] }
tar = "0.4"

[build-dependencies]
bindgen = "0.54"
glob = "0.3"
napi-build = { version = "0.1", path = "../build" }
regex = "1.3"
semver = "0.10"

[features]
default = []
# See the N-API Version Matrix https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix
napi2 = []
napi3 = []
napi4 = []
napi5 = []
napi6 = []
