[package]
name = "napi"
version = "0.4.6"
authors = ["Nathan Sobo <nathan@github.com>", "Yinan Long <lynweklm@gmail.com>"]
license = "MIT"
description = "N-API bindings"
readme = "README.md"
repository = "https://github.com/napi-rs/napi-rs"
keywords = ["NodeJS", "FFI", "NAPI", "n-api"]
edition = "2018"

[features]
libuv = ["futures"]
tokio_rt = ["futures", "tokio", "once_cell"]

[dependencies]
napi-sys = { version = "0.4", path = "../sys" }

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.tokio]
version = "0.2"
features = ["rt-core", "rt-threaded", "sync"]
optional = true

[dependencies.once_cell]
version = "1.4"
optional = true


[build-dependencies]
napi-build = { version = "0.2", path = "../build" }
