[package]
name = "napi-derive-example"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-rs = { path = "../napi" }
napi-rs-derive = { path = "../napi-derive" }

[build-dependencies]
napi-build = { path = "../build" }
