[package]
name = "test-module"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
napi-rs = { path = "../napi", features = ["libuv"] }
napi-rs-derive = { path = "../napi-derive" }
tokio = { version = "0.2", features = ["default", "fs"]}

[build-dependencies]
napi-build = { path = "../build" }
