[package]
authors = ["Nathan Sobo <nathan@github.com>", "Yinan Long <lynweklm@gmail.com>"]
description = "N-API bindings"
edition = "2018"
keywords = ["NodeJS", "Node", "FFI", "NAPI", "n-api"]
license = "MIT"
name = "napi"
readme = "README.md"
repository = "https://github.com/napi-rs/napi-rs"
version = "2.0.0-beta.4"

[features]
async = ["tokio_rt"]
compat-mode = []
default = ["napi3", "compat-mode"] # for most Node.js users
experimental = ["napi-sys/experimental"]
full = ["latin1", "napi8", "async", "serde-json", "experimental"]
latin1 = ["encoding_rs"]
napi1 = []
napi2 = ["napi1"]
napi3 = ["napi2", "napi-sys/napi3"]
napi4 = ["napi3", "napi-sys/napi4"]
napi5 = ["napi4", "napi-sys/napi5"]
napi6 = ["napi5", "napi-sys/napi6"]
napi7 = ["napi6", "napi-sys/napi7"]
napi8 = ["napi7", "napi-sys/napi8"]
serde-json = ["serde", "serde_json"]
tokio_rt = ["tokio", "once_cell", "napi4"]

[dependencies]
ctor = "0.1"
napi-sys = {version = "2.1.0", path = "../sys"}

[target.'cfg(windows)'.dependencies]
windows = {version = "0.28", features = ["Win32_System_WindowsProgramming", "Win32_System_LibraryLoader", "Win32_Foundation"]}

[dependencies.encoding_rs]
optional = true
version = "0.8"

[dependencies.tokio]
features = ["rt", "rt-multi-thread", "sync"]
optional = true
version = "1"

[dependencies.once_cell]
optional = true
version = "1"

[dependencies.serde]
optional = true
version = "1"

[dependencies.serde_json]
optional = true
version = "1"

[package.metadata.docs.rs]
all-features = true

[package.metadata.workspaces]
independent = true
