name: Linux-armv7

env:
  DEBUG: 'napi:*'
  CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: 'arm-linux-gnueabihf-gcc'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: stable - aarch64-unknown-linux-gnu - node@14
    runs-on: ubuntu-latest

    steps:
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          check-latest: true

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install armv7 toolchain
        run: rustup target add armv7-unknown-linux-gnueabihf

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: stable-linux-armv7-gnu-node@14-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: stable-linux-armv7-gnu-node@14-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-cache-linux-armv7-gnu-node@14-${{ hashFiles('yarn.lock') }}

      - name: Install cross compile toolchain
        run: sudo apt-get install gcc-arm-linux-gnueabihf -y

      - name: Install dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org

      - name: 'Build TypeScript'
        run: yarn build

      - name: Cross build native tests
        run: yarn build:test:armv7

      - name: Setup and run tests
        uses: docker://multiarch/ubuntu-core:armhf-focal
        with:
          args: >
            sh -c "
              apt-get update && \
              apt-get install -y ca-certificates gnupg2 curl && \
              curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
              apt-get install -y nodejs && \
              npm test
            "
